// @ts-nocheck
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Uwaga: `prisma/config` jest dostępny od Prisma 6+. Projekt używa Prisma 5.x,
// więc ten plik jest nieaktywny — zostawiamy go na potrzeby przyszłego upgrade'u.
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
